### ISSUE TITLE
GHC-Scholarships for Asian

### ISSUE THREAD

**Issue by Jaminy** [Ladies-Storm-Hackathons/GHC-Scholarships#23]
Hi,
Is there any GHC-scholarship for Asians?
Most of them mentioned here are only those who from USA.

**Comment by AsmaSwapna-zz** [comment]
Hey Jaminy, for women from STEM fields in South East Asia/ Asia there is opportunity to participate in GHC India section, I believe they are still accepting applications for submissions and scholarship/travel grants/stipends. 
The link might help you to grasp the glimpse better -http://ghcindia.anitaborg.org
