### ISSUE TITLE
Scholarships for 2017

### ISSUE THREAD

**Issue by RashaHussein** [Ladies-Storm-Hackathons/GHC-Scholarships#34]
Are you gonna update this with scholarships for this year? It seems scholarships by GHC themselves have already closed.

**Comment by aceyoung9** [comment]
Hey @RashaHussein ,

Freia, the former repository manager, graduated and has graciously transferred the repo to the LSH GitHub Org. So, yes, we'll be accepting updates via PR from the community. And with more more moderators, we'll have a faster turnaround time for merging.
