### ISSUE TITLE
Accenture Scholarship for GHC

### ISSUE THREAD

**Issue by Zoelewis** [Ladies-Storm-Hackathons/GHC-Scholarships#42]
Could you add the Accenture Scholarship details to the list for GHC? Newly launched this week - http://accenture.com/ghc2017 

Deadline is July 10th

Scholarship includes:

- Three-day conference pass
- Round-trip airfare
- Hotel accommodations
- Daily meal stipend
- An interview for a full-time role or internship
- A spotlight as a social media ambassador

**Comment by jericahuang** [comment]
Added, thanks! :)
