### ISSUE TITLE
Really minor thing - description

### ISSUE THREAD

**Issue by mtziemba** [Ladies-Storm-Hackathons/GHC-Scholarships#44]
The descriptions reads: 
Comprehensive list of student scholarships for the Grace Hopper Conference in 2016

We should change the year to 2017!

**Comment by jericahuang** [comment]
I'm unable to edit this description - @aliceyoung9 ?

**Comment by aceyoung9** [comment]
I just removed the year, since we've got a running archive going too. Thanks, @mtziemba and @jericahuang !
