### ISSUE TITLE
last date for facebook scholarship 

### ISSUE THREAD

**Issue by mhmohona** [Ladies-Storm-Hackathons/GHC-Scholarships#61]
Facebook Grace Hopper Scholarship's last date of submission is at June 29, 2018 at 11:59pm PST, not 30 June. 

https://www.facebook.com/careers/program/gracehopper2018/

**Comment by GunpreetAhuja** [comment]
Just a one minute error.

**Comment by jericahuang** [comment]
Resolved, thanks!
