### ISSUE TITLE
Submit Grace Hopper Award sponsored by Microsoft's Windows Insider Program

### ISSUE THREAD

**Issue by MichellePaison** [Ladies-Storm-Hackathons/GHC-Scholarships#69]
Hello! Might you please help me post the below? I was unable to create a New Pull Request and our award is currently live (until 8/22), so would greatly appreciate the support. Many thanks!

Windows Insider Program Women in Computing Award

Sponsoring Organization: Microsoft / Windows Insider Program
Amount: Mentoring at Microsoft Headquarters, ticket to the Grace Hopper Celebration, travel, lodging, meals - value of equivalent to up to $8500 
Application due date: August 8, 2018

The Windows Insider Program is offering an award for extraordinary women majoring in computer science or a related field. Award recipients will attend the Grace Hopper Celebration and related conference activities in Houston, TX from September 26-28, and travel to Redmond, WA (dates TBD) for mentoring at Microsoft Headquarters. The award is open to all women currently in the process of completing a university computer science or related degree program. Please visit our web site for complete rules: aka.ms/ghwip

**Comment by blossomica** [comment]
@MichellePaison - There was a PR on it I think last week, this one -> https://github.com/Ladies-Storm-Hackathons/GHC-Scholarships/pull/68 which was merged. It doesn't have as much details as you posted but it appears on the main repository page and it links to the website.

I have a question though, your post says "Application due date: August 8, 2018", but also "currently live (until 8/22)" and the website says August 22nd as the date due. So is the 8th of August an error?

**Comment by MichellePaison** [comment]
Hi, Gloria!

Many thanks for the quick reply. And apologies: I do, indeed, see the posting on the site. (You’re absolutely correct, Aug. 8 was an error – sorry about that!)

No need for further action, what is currently listed is correct! Truly appreciate the help here.

Thanks!
Michelle

________________________________

**Comment by blossomica** [comment]
You are welcome, @MichellePaison !
