### ISSUE TITLE
Is Twitter sponsorship only for Under-grads?

### ISSUE THREAD

**Issue by anjaliSelvaraj** [Ladies-Storm-Hackathons/GHC-Scholarships#71]
I could not create a pull request. 

In Twitter's Scholarship description, it is mentioned that the students enrolled in two year graduate program

"Full-time student completing your undergraduate study in 2019 or 2020 at a two or four year university/college or graduate program."

I just wanna make sure if a graduate student is qualified for Twitter's GHC scholarship, though its pretty late.

**Comment by blossomica** [comment]
@anjaliSelvaraj - Good catch! I'll try to see if I can create a pull request for your issue (even though I think it is pretty late as you said.)

From what I understand, based on what is written, I'd say it means this:

2 year degree -> Usually college 
4 year degree -> Usually university
Graduate program -> Usually master's, but usually also means PhD etc.

If you want to apply i'd say go for it!
