### ISSUE TITLE
Scholarship

### ISSUE THREAD

**Issue by LindaRZhang** [Ladies-Storm-Hackathons/GHC-Scholarships#76]
Hi,
 I notice the four scholarship provided said the deadline has past. Is it too late to apply for scholarship for the GHS Conference. Would there be any chance of other scholarships? Thank you for your time.

**Comment by blossomica** [comment]
Hello @Bakalmiyu, just thought of answering your question since you haven't got any response yet! I am not sure if you are eligible for this but check out these ones here and feel free to apply if you meet the requirements. -> https://ghc.anitab.org/2019-attend/opportunities-woc/#pathways

**Comment by mhmohona** [comment]
Hello @Bakalmiyu! 
Like previous years Facebook, Twitter, Windows Insider and some other scholarship opportunities are supposed to be announced within a few days. Keep an eye on this repository!

**Comment by diksha11s** [comment]
Are there any other scholarships to which we can still apply?

**Comment by SaiSriNarne** [comment]
Hey @diksha11s , Facebook is offering GHC 2019 Scholarships and the last date to submit an application is June 28th, 2019. Here is the link you can look in to https://www.facebook.com/careers/v2/jobs/2306282856126312
