### ISSUE TITLE
[RFC] Pooling diversity resources

### ISSUE THREAD

**Issue by svaksha** [Ladies-Storm-Hackathons/GHC-Scholarships#8]
Hi @freialobo,
I curate and maintain a Diversity-Index of grants, scholarships and FA that encourages diversity in STEM fields aimed at half the world's population, Women at http://svaksha.github.io/diversity-index
I had listed the [GHC event](https://github.com/svaksha/diversity-index/blob/master/di-conferences-events.md) but after I saw your GHC scholarship repo, I wanted to ask if you would like to collaborate and submit a PR. It would be nice to collaborate so that people can find resources easily. 
Thanks, Svaksha.

**Comment by freialobo** [comment]
Sure, I'll do that in the next few days :smile:

**Comment by svaksha** [comment]
Great, I look forward to it :+1:
