### ISSUE TITLE
Microsoft Windows Insider Program Women in Computing Award

### ISSUE THREAD

**Issue by MichellePaison** [Ladies-Storm-Hackathons/GHC-Scholarships#84]
Hello! Might you please post the following award, being offered for the second year running:

Microsoft Windows Insider Program - Women in Computing Award 
  
Sponsoring Organization: Microsoft / Windows Insider Program 
Amount: Trip to the Grace Hopper Celebration and special programming, including travel, lodging, meals - value of equivalent to up to $3000  
Application due date: July 10, 2019 
  
The Windows Insider Program is offering sponsorships for up to 14 extraordinary women majoring in computer science or a related field to attend the Grace Hopper Celebration. Winners will receive paid trips to attend Grace Hopper in Orlando, Florida from October 1-4, 2019, followed by a day of professional development on October 5, hosted by Microsoft and the Windows Insider Program. The award is open to all women currently in the process of completing a university computer science or related degree program. Please visit our web site for complete rules: aka.ms/WIC2019

**Comment by blossomica** [comment]
@MichellePaison - Hi there! I created a PR for your issue.

**Comment by MichellePaison** [comment]
Thank you ever so much, I’m so grateful! Do I need to take any further action here to get it posted? Thanks!

________________________________

**Comment by blossomica** [comment]
@MichellePaison  - You're welcome! No, you don't need to. A maintainer of the Ladies Storm Hackathon repository will need to review and merge the PR I created for your issue and then it will how up in the GHC Scholarship list.

**Comment by arientyse** [comment]
Hello Everyone! Has anyone heard back from Microsoft about the Windows Insider Women in Computing Scholarship? They stated in the Application Confirmation Email, that they would send their decisions out on August 1st. I haven't seen any posts or anything about it.

**Comment by shubhangibharti** [comment]
Almost all the results are out. Has anyone heard from Microsoft yet?

**Comment by Annielytix** [comment]
@michellepaison - will Microsoft be offering this again in 2010? Can you let me know on Teams chat or little r me via email ? I’m in the GAL - much thanks !!

**Comment by mhmohona** [comment]
@annedroid you mean 2020? 
Chances are high that they will offer this scholarship again as in the last few years they are offering it regularly. 
Check this to know about terms and condition in last year: https://insider.windows.com/en-us/community-contests-grace-hopper-celebration-about/
