### ISSUE TITLE
Wrong deadline mentioned for Facebook Grace Hopper Scholarship

### ISSUE THREAD

**Issue by shrija14** [Ladies-Storm-Hackathons/GHC-Scholarships#91]
29th June PDT is mentioned as the deadline for Facebook Grace Hopper Scholarship but its 28th June. This is really misleading.

**Comment by blossomica** [comment]
If you see a mistake you can create a corrective pull request. This being opensource means you can actively contribute to making things better.

**Comment by samsaid** [comment]
Does anyone know when Facebook will announce/if they did? I believe the page said it would be Aug 1 by midnight, however I haven't seen anyone post on LinkedIn.

**Comment by ncarbon** [comment]
@samsaid I got a rejection email on Aug 3rd. If you haven't gotten an email, maybe you're on a waitlist?

**Comment by blossomica** [comment]
@samsaid - I saw someone post they got it on August 1st

**Comment by samsaid** [comment]
Just saw a post as well, does anyone have an email I can contact them with?

**Comment by samsaid** [comment]
Just saw a post as well, is there an email I can contact them with?

**Comment by blossomica** [comment]
@samsaid - Couldn't find an email when I searched. Hoping by now they have responded!
